version: "2"
linters:
  enable:
    - misspell
    - revive
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: EXC0012
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
