version: "2"
linters:
  enable:
    - misspell
    - revive
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: EXC0012
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      checks:
        - all
        - '-SA1019' # Disabled since we know we have deprecated things that we can't update because of protobuf limitations

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
